export interface Insight {
  id: string;
  headline: string;
  body: string;
  impact: string;
  impactType: 'positive' | 'negative' | 'neutral';
  tag: string;
  timeAgo: string;
  saved: boolean;
}

export const INSIGHTS: Insight[] = [
  {
    id: 'i1',
    headline: 'Fed held rates steady. Your HYSA is still winning.',
    body: 'The Federal Reserve held interest rates at 5.25%–5.50% today. For VAULT members with high-yield savings accounts, this means you\'re still earning 4.8–5.1% on idle cash — 50x what a standard checking account pays.',
    impact: 'Money in a standard checking account loses real purchasing power — a HYSA earns 50x more for zero added risk',
    impactType: 'negative',
    tag: 'MACRO',
    timeAgo: '2h ago',
    saved: false,
  },
  {
    id: 'i2',
    headline: 'S&P 500 up 1.4% this week. Are you invested?',
    body: 'Markets rallied on strong jobs data. If you\'re not in the market, you\'re watching returns happen for other people. The historical average return is 10.7%/year — your HYSA earns 5%. The gap is the cost of staying on the sidelines.',
    impact: 'Sitting on the sidelines has a real cost — compound growth only works when you\'re in',
    impactType: 'neutral',
    tag: 'MARKETS',
    timeAgo: '5h ago',
    saved: true,
  },
  {
    id: 'i3',
    headline: 'The salary negotiation window is open. Most miss it.',
    body: 'Data from 40,000 salary negotiations shows the highest success rate (73%) comes at the 9–12 month mark in a role. You\'re in that window right now. The average successful negotiation added $11,400 to annual comp.',
    impact: 'You\'re in the optimal negotiation window right now',
    impactType: 'positive',
    tag: 'CAREER',
    timeAgo: '1d ago',
    saved: false,
  },
  {
    id: 'i4',
    headline: 'Credit card APRs hit 22.8% average. Carry no balance.',
    body: 'The average credit card APR in the US hit a record 22.8%. Carrying even a $1,000 balance costs $228/year in interest alone. At VAULT Gold tier, you qualify for partner cards at 17.9% — a 27% lower rate.',
    impact: 'Gold tier perk: access to 17.9% APR partner cards',
    impactType: 'positive',
    tag: 'CREDIT',
    timeAgo: '2d ago',
    saved: false,
  },
  {
    id: 'i5',
    headline: 'Inflation cooling. Your purchasing power is recovering.',
    body: 'CPI came in at 2.4% — the lowest in 3 years. In real terms, your salary has more purchasing power today than it did 18 months ago. This is also a signal that the Fed may cut rates, which could slightly lower HYSA yields in Q3.',
    impact: 'Lock in today\'s HYSA rates before potential cuts',
    impactType: 'neutral',
    tag: 'ECONOMY',
    timeAgo: '3d ago',
    saved: false,
  },
  {
    id: 'i6',
    headline: 'Tech layoffs hit 60,000 workers this month. Your emergency fund matters now.',
    body: 'Major tech firms announced 60,000 layoffs in the past 30 days. Across all sectors, the average job search takes 5.1 months. Financial advisors recommend 5–6 months of expenses saved — most people are under that threshold. One more month of buffer changes everything.',
    impact: 'Most people are 1–2 months short of the 5-month safety zone',
    impactType: 'negative',
    tag: 'ECONOMY',
    timeAgo: '4h ago',
    saved: false,
  },
  {
    id: 'i7',
    headline: 'Treasury yields at 4.9%. Bonds are worth looking at again.',
    body: '10-year Treasury yields hit 4.9% — the highest since 2007. For the first time in 15 years, risk-free government bonds offer a competitive return. If you\'re holding cash beyond your emergency fund, a Treasury ladder deserves a look.',
    impact: 'Risk-free 4.9% return available on idle cash above $10K',
    impactType: 'positive',
    tag: 'MARKETS',
    timeAgo: '6h ago',
    saved: false,
  },
  {
    id: 'i8',
    headline: 'Median new car price hits $48,000. The math on buying is brutal.',
    body: 'The median new car is now $48,000 — up 28% since 2020. At 7.4% auto loan rates, a 5-year loan costs $18,400 in interest alone. The average car loses 50% of its value in 3 years. This is one of the most expensive decisions most people make.',
    impact: 'A 3-year-old certified used car saves ~$22,000 vs buying new',
    impactType: 'negative',
    tag: 'MACRO',
    timeAgo: '8h ago',
    saved: false,
  },
  {
    id: 'i9',
    headline: 'Your credit score is worth $50,000 over a lifetime.',
    body: 'Going from a 650 to a 750 credit score saves an average of 1.5% on mortgage rates. On a $350,000 home, that\'s $52,500 in total interest saved. The two biggest levers: payment history (35%) and utilization (30%). Both are in your control.',
    impact: 'Every 50-point credit score improvement can save thousands on loans over your lifetime',
    impactType: 'positive',
    tag: 'CREDIT',
    timeAgo: '12h ago',
    saved: false,
  },
  {
    id: 'i10',
    headline: 'The average American retires with $87,000. That lasts 4 years.',
    body: 'Social Security replaces only 40% of pre-retirement income. The gap must come from savings. Someone retiring at 65 with $87,000 runs out of money by 69. The rule of thumb: 25x your annual expenses. At $60K/year spend, you need $1.5M.',
    impact: 'Most people need to 10x their savings rate to hit a real retirement target',
    impactType: 'neutral',
    tag: 'MACRO',
    timeAgo: '1d ago',
    saved: false,
  },
  {
    id: 'i11',
    headline: 'Remote work premium is evaporating. In-office pays more now.',
    body: 'New data shows fully remote workers earn 7.5% less than in-office peers in the same role. Hybrid workers earn 3.2% less. The gap is widening. If you\'re remote by choice, quantify what it\'s costing you — and whether the trade-off is worth it.',
    impact: 'Remote premium gap could cost $6,000–$15,000/year at your income',
    impactType: 'neutral',
    tag: 'CAREER',
    timeAgo: '2d ago',
    saved: false,
  },
  {
    id: 'i12',
    headline: 'Roth conversions are cheapest during market dips.',
    body: 'When markets are down 15–20%, converting traditional IRA funds to Roth costs less in taxes — you pay tax on a lower account value, but your gains after recovery are tax-free forever. Market dips are the best time to make this move.',
    impact: 'A $10K conversion today could save $4,200 in future taxes',
    impactType: 'positive',
    tag: 'MARKETS',
    timeAgo: '3d ago',
    saved: false,
  },
];
