import { WealthMove, VelocityScore, WealthWin, UserProfile } from '../types';

export const MOCK_SCORE: VelocityScore = {
  total: 647,
  savings: 72,
  investment: 61,
  debt: 55,
  spending: 68,
  weeklyChange: 47,
  percentile: 71,
  tier: 'GOLD',
  tierProgress: 0.66,
};

export const ALL_MOVES: WealthMove[] = [
  // ── SAVINGS ──────────────────────────────────────────────────────────
  {
    id: 's1',
    title: 'Dead money sitting idle',
    description: 'You have $2,340 in Chase checking earning 0.01%. A high-yield savings account pays 50x more. That gap is $117/yr for zero extra risk.',
    impact: '+$117/yr',
    impactValue: 117,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Move to HYSA',
  },
  {
    id: 's2',
    title: 'Emergency fund is 2 months short',
    description: 'You have 3.1 months of expenses saved. The safe zone is 5–6. One unexpected bill away from debt. Close the gap before anything else.',
    impact: 'Risk removed',
    impactValue: 5000,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Set up auto-save',
  },
  {
    id: 's3',
    title: 'Savings rate below your income tier',
    description: 'At your income, the median savings rate is 18%. You\'re at 11%. Closing that gap by just 4% adds $2,800/yr to your net worth.',
    impact: '+$2,800/yr',
    impactValue: 2800,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Adjust auto-transfer',
  },
  {
    id: 's4',
    title: 'Round-up savings doing almost nothing',
    description: 'Your Acorns account has $180. Round-up investing averages $12/month — that\'s fine, but a lump-sum index fund investment of the same amount returns 3x more long-term.',
    impact: '+$340 over 5 yrs',
    impactValue: 340,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Compare options',
  },

  // ── INVESTMENT ───────────────────────────────────────────────────────
  {
    id: 'i1',
    title: 'Free money left on the table',
    description: 'Your 401k is at 4%. Your employer matches up to 6%. That 2% gap costs you $1,200/year in free compensation. No investment beats a 100% instant return.',
    impact: '+$1,200/yr',
    impactValue: 1200,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Increase to 6%',
  },
  {
    id: 'i2',
    title: 'No Roth IRA open',
    description: 'At your income and tax bracket, a Roth IRA beats a traditional IRA. You pay taxes now at a lower rate than you will at retirement. Max is $7,000/yr. Start with $500.',
    impact: '$180K+ at 60',
    impactValue: 7000,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Open Roth IRA',
  },
  {
    id: 'i3',
    title: '401k allocation is too conservative',
    description: 'At your age, a 60/40 stock/bond split is leaving roughly 2–3% annual return on the table vs a 90/10 allocation. Over 20 years, that difference is $80,000+.',
    impact: '+$80K over 20 yrs',
    impactValue: 4000,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Rebalance now',
  },
  {
    id: 'i4',
    title: 'Cash sitting in brokerage',
    description: 'You have $1,100 in uninvested cash in your brokerage account. Every day it sits there it underperforms a basic index fund by ~0.03%. Put it to work.',
    impact: '+$88/yr',
    impactValue: 88,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Invest cash',
  },
  {
    id: 'i5',
    title: 'High-fee mutual funds',
    description: 'Two of your 401k funds charge 0.8%+ in expense ratios. An equivalent Vanguard index fund charges 0.03%. That fee gap costs $420/yr on your current balance.',
    impact: '+$420/yr',
    impactValue: 420,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Switch funds',
  },

  // ── DEBT ─────────────────────────────────────────────────────────────
  {
    id: 'd1',
    title: 'Credit card at 22.9% APR',
    description: 'You\'re carrying $1,800 on a card charging 22.9%. That\'s $412/yr in interest. Paying $200 extra/month clears it in 9 months and saves $280 in interest.',
    impact: 'Save $280',
    impactValue: 280,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Pay extra now',
  },
  {
    id: 'd2',
    title: 'Balance transfer opportunity',
    description: 'You qualify for a 0% APR balance transfer card for 15 months. Moving your $1,800 balance saves $412 in interest and clears the debt faster.',
    impact: 'Save $412',
    impactValue: 412,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check offers',
  },
  {
    id: 'd3',
    title: 'Student loan refinance window',
    description: 'Your student loan rate is 6.8%. Current refinance rates for your credit score are 5.1%. Refinancing saves $34/month — $408/yr — with no cash out of pocket.',
    impact: '+$408/yr',
    impactValue: 408,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check rates',
  },
  {
    id: 'd4',
    title: 'Minimum payments costing years',
    description: 'At minimum payments, your $3,200 credit card balance takes 11 years to clear and costs $2,100 extra in interest. Paying $120/month more cuts that to 26 months.',
    impact: 'Save $2,100',
    impactValue: 2100,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Adjust payment',
  },

  // ── SPENDING ─────────────────────────────────────────────────────────
  {
    id: 'sp1',
    title: 'Subscription ghost',
    description: 'You\'re paying $14.99/mo for Adobe Acrobat. Last opened: 4 months ago. That\'s $180/yr for software collecting digital dust.',
    impact: '+$180/yr',
    impactValue: 180,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Cancel it',
  },
  {
    id: 'sp2',
    title: 'Credit card rewards expiring',
    description: '$340 in Chase Ultimate Rewards points expire in 47 days. You haven\'t redeemed in 14 months. Redeem as cash back or travel — either way it\'s money.',
    impact: '+$340',
    impactValue: 340,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Claim rewards',
  },
  {
    id: 'sp3',
    title: 'Car insurance not shopped in 2 years',
    description: 'The average driver saves $480/yr by getting 3 competing quotes. Your policy renews in 6 weeks — ideal timing. Takes 20 minutes.',
    impact: '+$480/yr',
    impactValue: 480,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Get quotes',
  },
  {
    id: 'sp4',
    title: 'Dining spend is 140% of your peers',
    description: 'You spent $890 on dining last month. People your age and income in your city average $380. That $510 gap — redirected to savings — is $6,120/yr.',
    impact: '+$6,120/yr',
    impactValue: 6120,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Set a target',
  },
  {
    id: 'sp5',
    title: 'Gym membership unused',
    description: 'You\'ve been to the gym 3 times in 90 days. At $49/month that\'s $196 per visit. Pause it or find a $15/month alternative.',
    impact: '+$408/yr',
    impactValue: 408,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Pause membership',
  },
  {
    id: 'sp6',
    title: 'FSA funds expiring in 60 days',
    description: 'You have $380 left in your FSA that expires December 31. Use it on eligible expenses — glasses, dental, prescriptions — or lose it.',
    impact: 'Keep $380',
    impactValue: 380,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'See eligible items',
  },

  // ── OPPORTUNITY ──────────────────────────────────────────────────────
  {
    id: 'o1',
    title: 'Salary negotiation window is open',
    description: 'Your role in this city averages $12K more than your current salary. At 9 months in, you\'re in the highest-success negotiation window. 73% of people who ask, get.',
    impact: '+$12,000/yr',
    impactValue: 12000,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'See the data',
  },
  {
    id: 'o2',
    title: 'Tax loss harvesting opportunity',
    description: 'Two positions in your brokerage are down 8–12%. Selling to realize the loss offsets capital gains and can reduce your tax bill by up to $1,500 this year.',
    impact: 'Save ~$1,500 taxes',
    impactValue: 1500,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Review positions',
  },
  {
    id: 'o3',
    title: 'HSA as a stealth retirement account',
    description: 'If you\'re on a high-deductible health plan, an HSA is triple tax-advantaged. Max contribution ($4,150 single) grows tax-free and can be used for any expense at 65.',
    impact: '$4,150 tax-free/yr',
    impactValue: 4150,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Check eligibility',
  },
  {
    id: 'o4',
    title: 'Credit score 18 points from prime rate',
    description: 'Your score is 698. Prime rate lending starts at 720. 18 points could lower your next car loan by 1.2% — saving $840 over a 5-year loan.',
    impact: 'Save $840',
    impactValue: 840,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'See quick wins',
  },
  {
    id: 'o5',
    title: 'Referral bonuses unclaimed',
    description: 'You qualify for $200 in bank referral bonuses from 3 banks you already use. Sharing your referral link takes 2 minutes per bank.',
    impact: '+$600',
    impactValue: 600,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Get referral links',
  },
];

// Daily feed shows the first 7 — rotates in production
export const MOCK_MOVES: WealthMove[] = ALL_MOVES.slice(0, 7);

export const MOCK_WINS: WealthWin[] = [
  {
    id: '1',
    title: 'First $10K saved',
    subtitle: 'You hit a major milestone',
    value: '$10,000',
    date: new Date(2026, 3, 15),
    category: 'savings',
  },
  {
    id: '2',
    title: 'Gold tier unlocked',
    subtitle: 'Top 29% of wealth builders',
    value: 'Gold',
    date: new Date(2026, 4, 1),
    category: 'tier',
  },
  {
    id: '3',
    title: 'Debt-free on credit cards',
    subtitle: 'Paid off $3,200 in 6 months',
    value: '$3,200',
    date: new Date(2026, 4, 20),
    category: 'debt',
  },
];

export const MOCK_USER: UserProfile = {
  id: '1',
  name: 'Alex',
  tier: 'GOLD',
  score: MOCK_SCORE,
  streakDays: 23,
  wins: MOCK_WINS,
  joinedAt: new Date(2026, 0, 15),
};
