import { WealthMove, VelocityScore, WealthWin, UserProfile } from '../types';

export const MOCK_SCORE: VelocityScore = {
  total: 647,
  savings: 72,
  investment: 61,
  debt: 55,
  spending: 68,
  weeklyChange: 47,
  percentile: 71,
  tier: 'GOLD',
  tierProgress: 0.66,
};

export const ALL_MOVES: WealthMove[] = [
  // ── SAVINGS ──────────────────────────────────────────────────────────
  {
    id: 's1',
    title: 'Dead money sitting idle',
    description: 'Most checking accounts pay 0.01% interest. A high-yield savings account pays 50x more — same FDIC protection, zero added risk. The gap compounds against you every day.',
    impact: 'Up to +$500/yr',
    impactValue: 117,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Move to HYSA',
    lesson: {
      headline: 'The inflation tax on idle cash',
      body: 'Inflation runs ~3%/yr. Money at 0.01% loses real value every day. A HYSA at 5% means your savings actually grow instead of quietly shrinking.',
      xp: 10,
    },
  },
  {
    id: 's2',
    title: 'Build a real emergency fund',
    description: 'Financial advisors recommend 5–6 months of expenses saved before investing aggressively. Without it, one unexpected event sends you into debt at 20%+ APR.',
    impact: 'Risk eliminated',
    impactValue: 5000,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Set up auto-save',
    lesson: {
      headline: 'Why 5 months is the magic number',
      body: '3 months covers a short job loss. 5 months covers a real crisis — medical, layoff, unexpected expense. The difference is whether you go into debt or not.',
      xp: 10,
    },
  },
  {
    id: 's3',
    title: 'Close the savings rate gap',
    description: 'Top wealth builders save 20%+ of income. The national average is 4.6%. Every 1% more you save compounds over decades — small gaps become massive differences at retirement.',
    impact: '+$2,800/yr per %',
    impactValue: 2800,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Adjust auto-transfer',
    lesson: {
      headline: 'Your savings rate is your financial speed',
      body: 'Income matters less than what you keep. Every 1% more you save compounds over decades. The path to wealth is built in percentages, not windfalls.',
      xp: 10,
    },
  },
  {
    id: 's4',
    title: 'Round-up savings: upgrade the strategy',
    description: 'Round-up investing averages $12/month — painless, but slow. A direct auto-transfer of the same amount to an index fund returns 3x more long-term due to lower fees and compounding.',
    impact: '+$340 over 5 yrs',
    impactValue: 340,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Compare options',
    lesson: {
      headline: 'Round-ups feel good but think small',
      body: 'Behavioral psychology loves round-ups because they\'re painless. But $12/month is $144/yr. A one-time $144 index fund investment today compounds further than years of small round-ups.',
      xp: 10,
    },
  },

  // ── INVESTMENT ───────────────────────────────────────────────────────
  {
    id: 'i1',
    title: 'Capture your full employer 401k match',
    description: 'If your employer matches 401k contributions up to 6% and you contribute less, you\'re leaving free compensation on the table. No investment on earth offers a 100% instant return.',
    impact: 'Up to +$3,000/yr',
    impactValue: 1200,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Check your rate',
    lesson: {
      headline: 'A 100% return, guaranteed',
      body: 'There is no investment on earth with a 100% instant return. Your employer match is exactly that — every dollar you contribute up to the match threshold is doubled immediately.',
      xp: 10,
    },
  },
  {
    id: 'i2',
    title: 'Open a Roth IRA',
    description: 'A Roth IRA grows 100% tax-free. The 2026 max is $7,000/yr. Starting at 30, that\'s worth $500K+ at retirement — all untaxed. Every year you wait is permanent compounding lost.',
    impact: '$500K+ at 65',
    impactValue: 7000,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Open Roth IRA',
    lesson: {
      headline: 'Pay taxes now, never again',
      body: 'A Roth IRA uses after-tax dollars — the growth is 100% tax-free forever. Traditional IRA withdrawals are taxed as income at retirement. The younger you start, the bigger the difference.',
      xp: 10,
    },
  },
  {
    id: 'i3',
    title: 'Rebalance to age-appropriate allocation',
    description: 'Under 40, a 60/40 stock/bond split leaves 2–3% annual return on the table vs a 90/10 allocation. Over 20 years, that difference can exceed $80,000 on a typical balance.',
    impact: '+$80K over 20 yrs',
    impactValue: 4000,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Check allocation',
    lesson: {
      headline: 'Time horizon is your biggest asset',
      body: 'Under 40, your money has 25+ years to compound. Bonds reduce volatility but slash returns. A 90/10 split historically returns 7% vs 5% for 60/40 — that 2% gap is $80K over 20 years.',
      xp: 10,
    },
  },
  {
    id: 'i4',
    title: 'Put uninvested brokerage cash to work',
    description: 'Cash sitting in a brokerage account earns near-zero while index funds return ~10%/yr historically. Uninvested cash is a slow leak — indecision is a financial decision.',
    impact: 'Up to +$100/yr per $1K',
    impactValue: 88,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Invest cash',
    lesson: {
      headline: 'Cash in a brokerage is a tax on indecision',
      body: 'Index funds like VTSAX return ~10%/yr on average. Every day idle cash sits is a day compound interest isn\'t working for you. Indecision is a financial decision.',
      xp: 10,
    },
  },
  {
    id: 'i5',
    title: 'Switch to low-fee index funds',
    description: 'Actively managed mutual funds often charge 0.5–1.5% in fees. Equivalent Vanguard or Fidelity index funds charge 0.03%. On a $50K portfolio over 20 years, that fee gap is worth $40,000+.',
    impact: '+$40K over 20 yrs',
    impactValue: 420,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Compare funds',
    lesson: {
      headline: 'The fee you don\'t see costs the most',
      body: '0.8% doesn\'t sound like much. But on $50K over 20 years, the difference between 0.8% and 0.03% in fees is $40,000 in compounded returns. Fund fees are the silent destroyer of wealth.',
      xp: 10,
    },
  },

  // ── DEBT ─────────────────────────────────────────────────────────────
  {
    id: 'd1',
    title: 'Attack high-interest credit card debt',
    description: 'Credit cards average 22%+ APR. Every $1,000 carried costs $220/yr in interest — guaranteed, risk-free losses. No investment consistently beats paying off high-interest debt first.',
    impact: '22%+ guaranteed return',
    impactValue: 280,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Build payoff plan',
    lesson: {
      headline: 'Compound interest works both ways',
      body: 'Every principle that makes investing powerful also makes high-interest debt devastating. 22% compounding against you is the same math as 22% working for you — just in reverse.',
      xp: 10,
    },
  },
  {
    id: 'd2',
    title: 'Explore a balance transfer card',
    description: 'Many credit cards offer 0% APR for 12–18 months on balance transfers. Moving high-interest debt to a 0% card and aggressively paying it down is one of the cleanest financial arbitrage moves available.',
    impact: 'Save hundreds in interest',
    impactValue: 412,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check offers',
    lesson: {
      headline: '0% APR is legal arbitrage',
      body: 'If you owe money at 22% and can move it to 0%, you\'re not just saving interest — you\'re recapturing 22% guaranteed. That beats any stock market return, risk-free.',
      xp: 10,
    },
  },
  {
    id: 'd3',
    title: 'Refinance high-rate student loans',
    description: 'If you have private student loans above 6%, refinancing to a lower rate can save hundreds per year with no upfront cost. Takes 20 minutes to check rates and doesn\'t affect your credit score.',
    impact: 'Save $400+/yr',
    impactValue: 408,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check rates',
    lesson: {
      headline: 'Interest rate gaps are permanent wealth leaks',
      body: 'A 1.5% lower rate on a $30K loan over 10 years saves $5,000+. Refinancing is free to apply for and takes 20 minutes. Most people never do it.',
      xp: 10,
    },
  },
  {
    id: 'd4',
    title: 'Pay more than the minimum',
    description: 'Credit card minimums are calculated to maximize interest paid over time. On a $3,000 balance at 22% APR, minimums alone take 10+ years to clear and cost thousands extra in interest.',
    impact: 'Save years of payments',
    impactValue: 2100,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Set higher payment',
    lesson: {
      headline: 'Minimums are designed to make banks rich',
      body: 'Card companies calculate minimums to maximize interest paid over time. Paying even $100/month more changes the math entirely, cutting years off your payoff date.',
      xp: 10,
    },
  },

  // ── SPENDING ─────────────────────────────────────────────────────────
  {
    id: 'sp1',
    title: 'Audit your ghost subscriptions',
    description: 'The average American pays for 4–6 subscriptions they rarely or never use. At $15/month each, that\'s $720–1,080/yr on autopilot. A 10-minute audit finds them all.',
    impact: 'Up to +$1,080/yr',
    impactValue: 180,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Review subscriptions',
    lesson: {
      headline: 'Ghost subscriptions are the sneakiest wealth drain',
      body: 'Most people underestimate monthly subscriptions by 2–3x. $15/month feels trivial, but 10 of them is $1,800/yr. The ROI test: if you forgot about it, you don\'t need it.',
      xp: 10,
    },
  },
  {
    id: 'sp2',
    title: 'Redeem your credit card rewards',
    description: 'Credit card points expire, devalue, or get clawed back. Treating rewards like a real asset — and actively redeeming them for cash or travel — adds hundreds of dollars a year most people leave on the table.',
    impact: 'Reclaim what you earned',
    impactValue: 340,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Check your rewards',
    lesson: {
      headline: 'Points are a currency with an expiration date',
      body: 'Credit card rewards are real money in a different form. They expire, devalue, or get clawed back. Treating them like any other asset — actively managed — adds hundreds of dollars a year.',
      xp: 10,
    },
  },
  {
    id: 'sp3',
    title: 'Shop your car insurance',
    description: 'The average driver saves $480/yr by getting 3 competing quotes. Insurance companies charge loyal customers more than new ones. Shopping takes 20 minutes and has no downside.',
    impact: '+$480/yr on average',
    impactValue: 480,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Get quotes',
    lesson: {
      headline: 'Loyalty is punished in insurance',
      body: 'Insurance companies offer best prices to new customers and quietly raise rates on existing ones. Shopping every 2 years is a documented, repeatable way to save $400–500/yr in 20 minutes.',
      xp: 10,
    },
  },
  {
    id: 'sp4',
    title: 'Set a dining budget',
    description: 'Dining out is the #1 budget category people consistently underestimate. The national average is $350/month. Reducing by even 20% — one fewer restaurant meal per week — saves $800+/yr.',
    impact: 'Save $800+/yr',
    impactValue: 6120,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Set a target',
    lesson: {
      headline: 'Dining is the most visible savings lever',
      body: 'Dining spend is social and emotional — which is why it scales without you noticing. Cutting one meal out per week is $800/yr redirected toward wealth.',
      xp: 10,
    },
  },
  {
    id: 'sp5',
    title: 'Audit unused gym or fitness memberships',
    description: 'If you\'re paying $40–100/month for a gym you visit less than 4x/month, the per-visit cost exceeds a boutique class. Pause, downgrade, or switch to a cheaper option.',
    impact: 'Save $400–1,200/yr',
    impactValue: 408,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Review membership',
    lesson: {
      headline: 'Sunk cost blindness keeps subscriptions alive',
      body: 'The money is already gone — that\'s not the question. The question is whether continuing serves you. Per-visit cost math cuts through emotional justification.',
      xp: 10,
    },
  },
  {
    id: 'sp6',
    title: 'Use your FSA before it expires',
    description: 'Flexible Spending Accounts are use-it-or-lose-it. If you have an FSA, check your balance before December 31 — eligible expenses include glasses, dental, prescriptions, and hundreds of OTC items.',
    impact: 'Keep what\'s yours',
    impactValue: 380,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Check FSA balance',
    lesson: {
      headline: 'FSA money is pre-tax — losing it is a double loss',
      body: 'FSA contributions come out pre-tax. Letting it expire means you paid taxes on money you spent on nothing. Use-it-or-lose-it is real — and preventable.',
      xp: 10,
    },
  },

  // ── OPPORTUNITY ──────────────────────────────────────────────────────
  {
    id: 'o1',
    title: 'Negotiate your salary',
    description: '73% of people who ask for a raise get one. The average raise from negotiation is 7–10%. A single successful negotiation compounds through every future raise, bonus, and retirement contribution for the rest of your career.',
    impact: 'Up to +$10,000+/yr',
    impactValue: 12000,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'See the strategy',
    lesson: {
      headline: 'Every salary dollar compounds for life',
      body: 'A $5K raise at 30 isn\'t just $5K/yr. It\'s the base for every future raise, bonus percentage, and 401k match. A single successful negotiation is worth $200K+ over a career.',
      xp: 10,
    },
  },
  {
    id: 'o2',
    title: 'Tax loss harvesting',
    description: 'If you hold taxable investments with unrealized losses, selling to realize those losses can offset capital gains and reduce your tax bill. You can repurchase after 30 days. Almost nobody does this.',
    impact: 'Save on taxes this year',
    impactValue: 1500,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Learn how it works',
    lesson: {
      headline: 'The government shares your losses if you ask',
      body: 'Tax loss harvesting lets you sell a losing position to offset gains and reduce your tax bill. You can buy it back after 30 days. It\'s a legal rule almost nobody uses.',
      xp: 10,
    },
  },
  {
    id: 'o3',
    title: 'Maximize your HSA',
    description: 'If you\'re on a high-deductible health plan, an HSA is the only triple-tax-advantaged account available. Contributions are pre-tax, growth is tax-free, and withdrawals for medical expenses are tax-free. After 65, use it for anything.',
    impact: 'Up to $4,300 tax-free/yr',
    impactValue: 4150,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Check eligibility',
    lesson: {
      headline: 'Triple tax advantage — most people ignore it',
      body: 'Contributions pre-tax. Growth tax-free. Medical withdrawals tax-free. After 65, use it for anything. Most people treat an HSA as a checking account — it\'s actually the most powerful account you can have.',
      xp: 10,
    },
  },
  {
    id: 'o4',
    title: 'Improve your credit score',
    description: 'The difference between a 699 and 720 credit score can be 0.5–1% on a mortgage rate. On a $300K loan, that\'s $30,000+ over the life of the loan. Two biggest levers: on-time payments and utilization below 30%.',
    impact: 'Save $30K+ on a mortgage',
    impactValue: 840,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'See quick wins',
    lesson: {
      headline: 'Your credit score is a price tag on every loan',
      body: 'A 22-point score difference can change your mortgage rate by 0.5%. On a $300K loan, that\'s $30,000 over the life of the loan. On-time payments and low utilization are the fastest movers.',
      xp: 10,
    },
  },
  {
    id: 'o5',
    title: 'Bank and referral bonuses',
    description: 'Banks, brokerages, and credit card companies pay $100–500 to acquire new customers. These bonuses are real money for behavior you\'d do anyway — opening an account, making a purchase, or referring a friend.',
    impact: 'Up to $500+ per offer',
    impactValue: 600,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Find current offers',
    lesson: {
      headline: 'Bank bonuses are the cleanest arbitrage',
      body: 'Referral and signup bonuses are free money for behavior you\'d do anyway. Banks pay to acquire customers — you\'re just capturing that value.',
      xp: 10,
    },
  },

  // ── SAVINGS (continued) ──────────────────────────────────────────────────
  {
    id: 's5',
    title: 'Build a CD ladder before rates drop',
    description: 'CD rates at 5%+ won\'t last forever. A CD ladder — splitting savings into 3, 6, 9, 12-month CDs — locks in today\'s rates while keeping liquidity. Beats a standard HYSA by 0.3–0.8%.',
    impact: 'Lock in +$300/yr per $10K',
    impactValue: 300,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'See how it works',
    lesson: { headline: 'CD laddering: the best of both worlds', body: 'You lock in higher rates without sacrificing access. As each CD matures, you reinvest at current rates or spend it — full control, maximum yield.', xp: 10 },
  },
  {
    id: 's6',
    title: 'Save your raise before you spend it',
    description: 'When you get a raise, lifestyle inflation usually absorbs it within 90 days. Routing the after-tax difference directly to savings before it hits your checking account is how real wealth accumulates.',
    impact: '+$1,200–4,000/yr',
    impactValue: 2400,
    category: 'savings',
    effort: 'instant',
    actionLabel: 'Set up now',
    lesson: { headline: 'Lifestyle inflation is the silent raise thief', body: 'Most raises evaporate into nicer dinners and upgraded subscriptions. Automating savings of your raise before adjusting your lifestyle is the single most powerful wealth-building habit.', xp: 10 },
  },
  {
    id: 's7',
    title: 'Apply the 50% windfall rule',
    description: 'Bonuses, tax refunds, and unexpected income are wealth-building shortcuts — if you don\'t spend them. The 50% rule: save at least half of any windfall, spend the rest guilt-free.',
    impact: '+$500–5,000 per windfall',
    impactValue: 1200,
    category: 'savings',
    effort: 'instant',
    actionLabel: 'Set the rule',
    lesson: { headline: 'Windfalls are the fastest path forward', body: 'The average tax refund is $3,200. Investing all of it and never touching it grows to $55K over 30 years. Most people spend it within 2 weeks.', xp: 10 },
  },
  {
    id: 's8',
    title: 'Eliminate ATM fees forever',
    description: 'ATM fees average $4–5 per transaction. At 3x/month that\'s $180/yr for accessing your own money. Online banks like Ally or Charles Schwab reimburse all ATM fees nationwide — automatically.',
    impact: 'Save $180+/yr',
    impactValue: 180,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Switch accounts',
    lesson: { headline: 'ATM fees are a tax on convenience', body: 'Every ATM fee is paying for the privilege of accessing your own money. One account switch eliminates this permanently — most online banks reimburse all fees.', xp: 10 },
  },
  {
    id: 's9',
    title: 'Build a sinking fund for irregular expenses',
    description: 'Car repairs, vet bills, home maintenance, and annual subscriptions aren\'t surprises — they\'re predictable. A sinking fund (saving monthly for known future costs) eliminates debt-funded emergencies.',
    impact: 'End debt-funded emergencies',
    impactValue: 1500,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Set up fund',
    lesson: { headline: 'Irregular expenses aren\'t emergencies — they\'re predictable', body: 'Your car will need repairs. Your roof will eventually leak. Saving $100/month into a dedicated account means when it happens, you pay cash — not 22% credit.', xp: 10 },
  },
  {
    id: 's10',
    title: 'Automate savings on payday — not month-end',
    description: 'People who save whatever\'s left at month-end save 3x less than those who automate on payday. Treat savings like rent: a non-negotiable payment to your future self that leaves first.',
    impact: 'Save 3x more automatically',
    impactValue: 2400,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Automate it',
    lesson: { headline: 'Pay yourself first is a law, not a suggestion', body: 'Saving what\'s left relies on willpower against a month of spending decisions. Automating before you see the money removes willpower from the equation entirely.', xp: 10 },
  },
  {
    id: 's11',
    title: 'Use Treasury bills as a HYSA alternative',
    description: 'T-bills (3–12 month U.S. government bonds) currently yield 5.1%+ and are exempt from state income tax. For high earners in a 6%+ state tax bracket, T-bills beat HYSAs on after-tax yield.',
    impact: 'Extra 0.3–0.6% after tax',
    impactValue: 400,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Explore T-bills',
    lesson: { headline: 'State tax exemption makes T-bills quietly superior', body: 'A T-bill yielding 5.1% in a 6% state is worth 5.4% vs a HYSA of the same rate. That gap matters on large balances.', xp: 10 },
  },
  {
    id: 's12',
    title: 'Set up separate savings buckets',
    description: 'Keeping all savings in one account blurs goals and invites spending. Three buckets — emergency fund, short-term goals, long-term goals — with automatic monthly contributions eliminates decision fatigue.',
    impact: 'Hit goals 2x faster',
    impactValue: 1800,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Create buckets',
    lesson: { headline: 'Money with a label is 3x less likely to be spent', body: 'Separate accounts for separate goals use psychology to enforce discipline automatically. Mental accounting is a feature, not a bug.', xp: 10 },
  },
  {
    id: 's13',
    title: 'Buy I-Bonds as an inflation hedge',
    description: 'Series I Savings Bonds from TreasuryDirect pay a rate tied to inflation — currently above 4%. They\'re state-tax free, federally guaranteed, and have no market risk. Limit is $10,000/yr per person.',
    impact: 'Inflation-proof up to $10K/yr',
    impactValue: 400,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Buy I-Bonds',
    lesson: { headline: 'I-Bonds: risk-free and inflation-adjusted', body: 'No investment guarantees you keep up with inflation — except I-Bonds, which are indexed to CPI. The $10K annual limit is the only catch.', xp: 10 },
  },
  {
    id: 's14',
    title: 'Do a one-week no-spend challenge',
    description: 'Cut all discretionary spending for 7 days — no restaurants, no online shopping, no entertainment purchases. The average person saves $180–300 in a single week and identifies permanent spending habits to cut.',
    impact: '$180–300 in one week',
    impactValue: 220,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Start this week',
    lesson: { headline: 'A no-spend week makes spending visible', body: 'Cutting everything for 7 days reveals which habits are genuine needs and which are automated decisions you never questioned. Most people find 2–3 habits to cut permanently.', xp: 10 },
  },
  {
    id: 's15',
    title: 'Join a credit union for better rates',
    description: 'Credit unions are not-for-profit and pass savings to members. Average credit union savings rates run 0.3–0.5% higher than big banks, and loan rates run 1–2% lower. Same FDIC-equivalent insurance coverage.',
    impact: 'Better rates, same protection',
    impactValue: 350,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Find credit unions',
    lesson: { headline: 'Credit unions answer to members, not shareholders', body: 'That difference shows up directly in the rates you earn on savings and pay on loans. Everything else is the same — same deposit insurance, same ATM networks.', xp: 10 },
  },
  {
    id: 's16',
    title: 'Set a hard limit on checking account cash',
    description: 'Keeping more than 2 months of expenses in checking is idle money. Set a "max checking balance" rule: anything above your threshold auto-transfers to your HYSA on the 1st of each month.',
    impact: '+$300–800/yr on idle cash',
    impactValue: 500,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Set threshold',
    lesson: { headline: 'Checking is a transit account, not a savings account', body: 'Money sitting in checking earns near 0%. Every dollar above your 2-month buffer should be working elsewhere. The auto-transfer removes the friction.', xp: 10 },
  },
  {
    id: 's17',
    title: 'Save into a Money Market fund',
    description: 'Money market funds in brokerage accounts (like Fidelity SPAXX or Vanguard VMFXX) currently yield 5%+ with same-day liquidity. Often higher than most HYSAs with no bank transfer delays.',
    impact: 'Higher yield, instant liquidity',
    impactValue: 450,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Check money markets',
    lesson: { headline: 'Money market funds are the forgotten HYSA upgrade', body: 'SPAXX and similar funds are essentially HYSAs inside your brokerage — with higher yields and instant availability for investing. Most people never enable them as a default sweep.', xp: 10 },
  },
  {
    id: 's18',
    title: 'Increase savings rate with every raise',
    description: 'Commit now: every future raise gets split — 50% to savings, 50% to lifestyle. You never feel the savings half because your lifestyle still improves. This one rule builds more wealth than any budget.',
    impact: 'Permanent savings acceleration',
    impactValue: 3000,
    category: 'savings',
    effort: 'instant',
    actionLabel: 'Commit to the rule',
    lesson: { headline: 'The raise split: you can\'t miss money you never had', body: 'Pre-committing to save half of future raises sidesteps willpower entirely. Your lifestyle still grows — just at half the rate of your income. The wealth gap compounds silently.', xp: 10 },
  },
  {
    id: 's19',
    title: 'Keep an "opportunity fund" above emergency fund',
    description: 'Beyond your 6-month emergency fund, a separate opportunity fund (3–6 months more) lets you say yes to career pivots, investment deals, and unexpected opportunities without going into debt.',
    impact: 'Say yes to life without debt',
    impactValue: 5000,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Build the buffer',
    lesson: { headline: 'Emergency fund = defense. Opportunity fund = offense.', body: 'Wealthy people maintain cash not just to absorb shocks but to capitalize on them. The difference between an emergency and an opportunity is often just having the cash ready.', xp: 10 },
  },

  // ── INVESTMENT (continued) ───────────────────────────────────────────────
  {
    id: 'i6',
    title: 'Max your 401k — not just the match',
    description: 'Capturing employer match is step 1. Maxing your full 401k contribution ($23,500 in 2026) is step 2. The tax deferral alone saves $5,000–8,000/yr for someone in the 22–24% bracket.',
    impact: 'Save $5K–8K in taxes/yr',
    impactValue: 6000,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Increase contributions',
    lesson: { headline: 'The tax benefit is the return — before investing', body: 'Every dollar in a traditional 401k reduces your taxable income. At 22%, $23,500 contributed saves $5,170 in federal taxes alone — before a single market return.', xp: 10 },
  },
  {
    id: 'i7',
    title: 'Dollar-cost average during downturns',
    description: 'Market drops feel catastrophic. They\'re actually sale events. Investors who keep contributing during pullbacks buy more shares at lower prices — their average cost falls, and recovery gains are amplified.',
    impact: 'Turn volatility into advantage',
    impactValue: 3200,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Keep investing',
    lesson: { headline: 'Downturns are sales. Buy, don\'t flee.', body: 'The S&P 500 has recovered from every correction in history. Investors who bought during the 2020 crash saw 100% gains within 13 months. Fear is the enemy of wealth.', xp: 10 },
  },
  {
    id: 'i8',
    title: 'Check if you qualify for backdoor Roth',
    description: 'If your income exceeds Roth IRA limits ($161K single / $240K married in 2026), the backdoor Roth lets you contribute through a traditional IRA conversion. It\'s legal, common, and almost nobody knows about it.',
    impact: '$7,000/yr tax-free growth',
    impactValue: 7000,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'See how it works',
    lesson: { headline: 'The backdoor Roth: legal loophole for high earners', body: 'Congress created income limits for Roth IRA but left in the conversion path. High earners who miss this move pay more in taxes at retirement — permanently.', xp: 10 },
  },
  {
    id: 'i9',
    title: 'Add international exposure to your portfolio',
    description: 'US-only portfolios miss 40% of global equity value. International stocks periodically outperform US. A 20% international allocation historically reduces volatility without reducing long-term returns.',
    impact: 'Better risk-adjusted returns',
    impactValue: 2800,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Check allocation',
    lesson: { headline: 'The US is 60% of global markets, not 100%', body: 'Owning only US stocks means owning nothing during periods when international markets outperform. Global diversification is the only free lunch in investing.', xp: 10 },
  },
  {
    id: 'i10',
    title: 'Increase your 401k by just 1%',
    description: 'One percentage point more in a 401k at 30 contributes to a $97,000 larger balance at 65 on a $70K salary. Most people don\'t feel a 1% decrease in their paycheck — and they never reverse it.',
    impact: '+$97K at retirement per 1%',
    impactValue: 1200,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Do it now',
    lesson: { headline: 'You won\'t feel 1% — you\'ll feel the result', body: 'At $70K salary, 1% is $700/yr — about $27/paycheck. You won\'t notice it. Invested at 7% over 35 years, your future self gets $97,000 more. That is the cleanest trade in personal finance.', xp: 10 },
  },
  {
    id: 'i11',
    title: 'Find the lowest-fee option in your 401k',
    description: 'Most 401k plans offer both institutional (cheap) and retail (expensive) versions of similar funds. Finding the lowest-expense-ratio option for your target allocation can save 0.3–1%/yr — worth $15K+ over 20 years.',
    impact: '+$15K+ over 20 years',
    impactValue: 750,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Review options',
    lesson: { headline: 'Same fund, different fee — a $15K difference', body: '0.6% vs 0.03% sounds trivial. On a $100K balance over 20 years, that\'s $17,000 less in your pocket. Your 401k plan may offer cheaper alternatives you haven\'t selected.', xp: 10 },
  },
  {
    id: 'i12',
    title: 'Switch to a target-date fund',
    description: 'Target-date funds automatically adjust from aggressive to conservative as your retirement year approaches. Simple, diversified, and they beat most manually managed portfolios over 20+ years due to discipline and low fees.',
    impact: 'Set it, forget it, win',
    impactValue: 4000,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Find your date fund',
    lesson: { headline: 'The best portfolio is one you never touch', body: 'Portfolios with fewer interventions outperform actively managed ones. A target-date fund automates discipline — the hardest part of investing.', xp: 10 },
  },
  {
    id: 'i13',
    title: 'Invest your bonus the same day it arrives',
    description: 'The window between receiving a bonus and spending it is 2–4 weeks for most people. Investing it the same day eliminates the temptation to absorb it into lifestyle expenses.',
    impact: 'Keep your wealth acceleration',
    impactValue: 5000,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Set the rule now',
    lesson: { headline: 'The first 48 hours decide what a bonus becomes', body: 'Once a bonus becomes part of your mental "available money," it disappears. Investing it the day it lands — before any spending decisions — is the only reliable strategy.', xp: 10 },
  },
  {
    id: 'i14',
    title: 'Open a 529 college savings plan',
    description: 'A 529 plan grows tax-free for education expenses. Contributions are state-deductible in most states. Starting at birth vs. age 10 can mean $100,000+ more due to compound growth.',
    impact: '$100K+ more vs. starting late',
    impactValue: 3000,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Open a 529',
    lesson: { headline: '529s are IRAs for education — start early', body: 'College costs grow ~5%/yr. A 529 started at birth gives 18 years of compound growth. Starting at 10 gives 8 — you need double the contributions for the same result.', xp: 10 },
  },
  {
    id: 'i15',
    title: 'Ask HR about mega backdoor Roth',
    description: 'Some 401k plans allow after-tax contributions up to $70,000/yr that can be converted to Roth. This is the mega backdoor Roth — one of the most powerful wealth tools available to high earners who know about it.',
    impact: 'Up to $46K more Roth space/yr',
    impactValue: 10000,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Ask HR today',
    lesson: { headline: 'The mega backdoor Roth: the most underused wealth tool', body: 'A quick email to HR asking if after-tax 401k contributions with in-plan Roth conversion is supported takes 2 minutes and could unlock $46K/yr in additional Roth space.', xp: 10 },
  },
  {
    id: 'i16',
    title: 'Enable dividend reinvestment (DRIP)',
    description: 'Dividend reinvestment compounds your position automatically — dividends buy more shares, those shares generate more dividends, indefinitely. Over 20 years, DRIP typically adds 30–40% to total returns.',
    impact: '+30–40% to long-term returns',
    impactValue: 8000,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Enable DRIP',
    lesson: { headline: 'Reinvested dividends are the compounding accelerant', body: 'Cash dividends in your account feel like income — and get spent. Reinvested dividends quietly buy more shares. Over 30 years, the difference is often 40% more wealth.', xp: 10 },
  },
  {
    id: 'i17',
    title: 'Update your beneficiary designations',
    description: 'Beneficiary forms on 401ks, IRAs, and life insurance override your will. Ex-spouse from 2012 still listed? They could legally inherit your retirement savings. Review all accounts and update today.',
    impact: 'Your assets go to who you choose',
    impactValue: 25000,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Review now',
    lesson: { headline: 'Beneficiary forms override your will — always', body: 'Courts repeatedly side with outdated beneficiary forms over clearly stated wills. An ex-spouse or deceased parent could inherit everything if you haven\'t updated your paperwork.', xp: 10 },
  },
  {
    id: 'i18',
    title: 'Optimize asset location across accounts',
    description: 'Where you hold assets matters as much as what you hold. Bonds belong in tax-deferred accounts. Growth stocks belong in Roth. Getting location right can add 0.5–1%/yr to after-tax returns — free money.',
    impact: '+0.5–1%/yr after-tax',
    impactValue: 1800,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Optimize placement',
    lesson: { headline: 'Asset location: the tax optimization most investors miss', body: 'A high-dividend bond fund in a taxable account creates unnecessary tax drag. Moving it to a 401k and growth stocks to Roth adds hundreds per year in tax savings with no added risk.', xp: 10 },
  },
  {
    id: 'i19',
    title: 'Add REITs for real estate exposure',
    description: 'Real estate is the #1 wealth builder for American millionaires — but buying property isn\'t the only way in. REITs give you diversified real estate returns through the stock market, with no landlord headaches.',
    impact: 'Real estate without the work',
    impactValue: 3500,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Explore REITs',
    lesson: { headline: 'REITs: real estate wealth without the toilets', body: 'REITs are legally required to distribute 90% of income as dividends. Historically they\'ve matched or beaten the S&P 500 with lower correlation — real diversification.', xp: 10 },
  },
  {
    id: 'i20',
    title: 'Time in market beats timing the market',
    description: 'Missing just the 10 best trading days per decade cuts returns by 50%. The best days happen during the most chaotic markets — exactly when scared investors sell. Staying invested is the strategy.',
    impact: '2x returns vs. market timers',
    impactValue: 15000,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Stay invested',
    lesson: { headline: 'The best days happen when you most want to sell', body: 'Missing the 10 best days over 20 years halves your portfolio. Those days cluster around market bottoms — when fear peaks. Panic selling is the single most expensive financial mistake.', xp: 10 },
  },
  {
    id: 'i21',
    title: 'Invest in yourself with a certification',
    description: 'A relevant professional certification increases earning potential by $8,000–25,000/yr on average. The ROI on career education often exceeds the stock market — with no market risk attached.',
    impact: '+$8K–25K/yr earning potential',
    impactValue: 15000,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Find the right cert',
    lesson: { headline: 'Human capital is the highest-returning investment', body: 'The stock market returns ~10%/yr on average. A certification that raises your salary by $10K returns 200–2,000% on a $500–5,000 investment. Career capital beats financial capital — especially early.', xp: 10 },
  },
  {
    id: 'i22',
    title: 'Consider municipal bonds if in a high tax bracket',
    description: 'If you\'re in the 24%+ federal bracket, municipal bonds (tax-exempt interest) can beat corporate bonds on after-tax yield. A muni yielding 3.5% equals a taxable bond at 4.6% for someone in the 24% bracket.',
    impact: 'Higher after-tax bond yield',
    impactValue: 900,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Calculate your breakeven',
    lesson: { headline: 'Munis: taxable equivalent yield changes the math', body: 'For high earners, the tax exemption flips munis from worse to better than corporates. The higher your bracket, the wider the advantage.', xp: 10 },
  },
  {
    id: 'i23',
    title: 'Keep investing even when the market is flat',
    description: 'Flat markets feel pointless — but they\'re where dollar-cost averaging accumulates shares at reasonable prices. The gains that follow flat periods are historically above average. Consistency is the edge.',
    impact: 'Compound without interruption',
    impactValue: 4000,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Stay the course',
    lesson: { headline: 'Flat periods are loading phases — not wasted time', body: 'The S&P 500\'s best 10-year returns historically followed flat or negative periods. Investors who quit during the flat phase miss the entire gain.', xp: 10 },
  },

  // ── DEBT (continued) ────────────────────────────────────────────────────
  {
    id: 'd5',
    title: 'Use the debt avalanche — pay highest rate first',
    description: 'Pay minimums on all debts. Put every extra dollar toward your highest-interest debt first. When it\'s paid, roll that payment to the next highest. Mathematically optimal — saves the most interest of any payoff method.',
    impact: 'Pay off months faster',
    impactValue: 1800,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Build your plan',
    lesson: { headline: 'Avalanche method: math beats emotion', body: 'Every extra dollar toward the highest-rate debt saves more in interest than any other approach. Once you see the math, the decision is obvious.', xp: 10 },
  },
  {
    id: 'd6',
    title: 'Refinance your auto loan',
    description: 'If you took out a car loan when your credit score was lower than it is today, refinancing to a better rate could save $1,000–3,000 over the remaining term. Lenders don\'t lower your rate automatically.',
    impact: 'Save $1K–3K on your car',
    impactValue: 1800,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check your rate',
    lesson: { headline: 'Your credit improved — your rate didn\'t', body: 'Lenders don\'t automatically lower your rate when your credit score rises. You have to ask — or refinance. A 2% drop on a $20K balance over 3 years saves over $1,200.', xp: 10 },
  },
  {
    id: 'd7',
    title: 'Call and negotiate your credit card APR',
    description: 'Two-thirds of cardholders who call their issuer and ask for a lower APR get one. Average reduction is 6 percentage points. A 10-minute call on a $5K balance saves $300/yr in interest.',
    impact: 'Save $300+/yr in 10 minutes',
    impactValue: 300,
    category: 'debt',
    effort: 'instant',
    actionLabel: 'Make the call',
    lesson: { headline: 'Your credit card company will negotiate — if you ask', body: 'Credit card issuers want to keep you. If you have a decent payment history, calling and asking for a rate reduction works 67% of the time. Most people never ask.', xp: 10 },
  },
  {
    id: 'd8',
    title: 'Negotiate your medical bills',
    description: 'Hospitals discount bills for cash payments and often write off significant portions for patients who ask. Most people pay the sticker price. Calling the billing department and asking for a hardship discount commonly saves 20–50%.',
    impact: 'Save 20–50% on medical bills',
    impactValue: 800,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Learn the script',
    lesson: { headline: 'Medical bills are starting points, not final invoices', body: 'Hospital chargemaster prices are the ceiling — not the price. Uninsured discounts, charity care programs, and billing negotiations are available to anyone who asks.', xp: 10 },
  },
  {
    id: 'd9',
    title: 'Use a personal loan to consolidate credit card debt',
    description: 'Personal loans for consolidation average 11–14% APR — vs 22%+ on credit cards. Moving $10K of card debt to a personal loan and not using the cards saves $800–1,100/yr in interest immediately.',
    impact: 'Cut interest rate in half',
    impactValue: 900,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Compare rates',
    lesson: { headline: 'Consolidation done right saves thousands', body: 'Pay 13% instead of 22%, and your $10K balance costs $1,300/yr instead of $2,200. The trap is using the freed cards again — discipline required.', xp: 10 },
  },
  {
    id: 'd10',
    title: 'Freeze card use during payoff',
    description: 'Paying down credit card debt while still using the card is like bailing a boat with the tap open. Switching to debit during payoff accelerates debt elimination and reveals real spending habits.',
    impact: 'Eliminate the debt spiral',
    impactValue: 1200,
    category: 'debt',
    effort: 'instant',
    actionLabel: 'Pause card use',
    lesson: { headline: 'You can\'t dig out while still digging', body: 'Every new charge during payoff extends the timeline and increases total interest paid. A temporary switch to debit removes the friction of simultaneous building and tearing down.', xp: 10 },
  },
  {
    id: 'd11',
    title: 'Apply for income-driven student loan repayment',
    description: 'Federal student loans offer income-driven repayment plans that cap payments at 5–10% of discretionary income. Some plans lead to forgiveness after 20–25 years. Millions who qualify never apply.',
    impact: 'Cut monthly payments up to 50%',
    impactValue: 2400,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check eligibility',
    lesson: { headline: 'Federal loan relief exists — most people don\'t claim it', body: 'SAVE, IBR, and PSLF plans can dramatically reduce federal student loan debt. Private loans don\'t qualify — but federal loans almost always do.', xp: 10 },
  },
  {
    id: 'd12',
    title: 'Dispute errors on your credit report',
    description: 'One in five credit reports contains an error. Disputing and removing an inaccurate negative item can raise your score 20–100 points, lowering rates on every future loan. Free reports at AnnualCreditReport.com.',
    impact: '+20–100 credit score points',
    impactValue: 2000,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Pull your report',
    lesson: { headline: '20% of credit reports have errors — check yours', body: 'The FTC found 1 in 5 people have material errors on their credit report. A single inaccurate collection account removed can move your score 50+ points — changing your mortgage rate permanently.', xp: 10 },
  },
  {
    id: 'd13',
    title: 'Pay credit cards twice a month',
    description: 'Paying your credit card balance twice a month (mid-cycle and at statement) keeps utilization low throughout the month, not just at the statement date. This alone can raise your credit score 15–30 points.',
    impact: '+15–30 credit score points',
    impactValue: 1500,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Set biweekly reminders',
    lesson: { headline: 'Credit scores see your balance mid-cycle too', body: 'Lenders report your balance to bureaus monthly — but not always at statement date. Carrying a low mid-cycle balance means lower utilization in the report regardless of when.', xp: 10 },
  },
  {
    id: 'd14',
    title: 'Use the debt snowball for motivation',
    description: 'If you\'re struggling with motivation, the snowball method — paying smallest balances first — creates early wins that keep you going. Research shows it leads to faster debt payoff for most people despite paying more interest.',
    impact: 'Pay off debt 15% faster',
    impactValue: 1000,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'List your debts',
    lesson: { headline: 'Psychology matters more than math when motivation is low', body: 'Early wins in debt payoff increase follow-through dramatically. The snowball method is less mathematically optimal but more behaviorally optimal — and behavior is what actually pays off debt.', xp: 10 },
  },
  {
    id: 'd15',
    title: 'Never let a debt go to collections',
    description: 'A single collection account drops your credit score 50–100 points and stays on your report 7 years. If you can\'t pay a bill, call the creditor before it reaches 60 days late — hardship plans are always available.',
    impact: 'Protect 50–100 score points',
    impactValue: 3000,
    category: 'debt',
    effort: 'instant',
    actionLabel: 'Call before 60 days',
    lesson: { headline: 'Creditors prefer a call to a collection agency', body: 'Selling debt to collections gives a creditor 20–40 cents on the dollar. They\'d rather work with you directly. A hardship plan with a creditor beats a collection account every time.', xp: 10 },
  },
  {
    id: 'd16',
    title: 'Pay off collections strategically',
    description: 'Paying an old collection doesn\'t remove it from your report — it just changes the status. Before paying an old collection, request a "pay for delete" in writing. Many collection agencies will agree.',
    impact: 'Remove negative marks entirely',
    impactValue: 2500,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Request pay for delete',
    lesson: { headline: '"Pay for delete" is a legitimate negotiation tactic', body: 'Collection agencies buy debt for pennies on the dollar. They have room to negotiate. A written pay-for-delete agreement clears the account from your report entirely — worth far more than just paying.', xp: 10 },
  },

  // ── SPENDING (continued) ────────────────────────────────────────────────
  {
    id: 'sp7',
    title: 'Negotiate your internet and cable bill',
    description: 'Telecom companies retain customers by offering new-customer rates to existing ones — but only when asked. A 10-minute call typically yields $20–40/month in savings or added services at no cost.',
    impact: 'Save $240–480/yr',
    impactValue: 360,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Make the call',
    lesson: { headline: 'Telecoms will lower your bill — if you threaten to leave', body: 'Customer retention departments have authority to discount by 20–40%. They don\'t call you. You have to call them. Mentioning a competitor quote triples your success rate.', xp: 10 },
  },
  {
    id: 'sp8',
    title: 'Audit annual fees on all credit cards',
    description: 'Many people pay $95–695/yr in credit card annual fees without reviewing whether the benefits still make sense. A card that was valuable in 2021 may have worse benefits now — or benefits you no longer use.',
    impact: 'Reclaim $95–695/yr',
    impactValue: 350,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Review all cards',
    lesson: { headline: 'Annual fees require annual audits', body: 'Card benefits change. Your spending changes. A travel card with no travel is just a $550/yr fee. Review each card once a year — cancel or downgrade anything whose benefits don\'t exceed its cost.', xp: 10 },
  },
  {
    id: 'sp9',
    title: 'Master grocery shopping: list, timing, unit price',
    description: 'Three levers cut grocery bills 20–30% with no sacrifice: shop with a list (reduces impulse spending 32%), shop Tuesday or Wednesday, and compare unit prices — not package prices.',
    impact: 'Save $80–150/month',
    impactValue: 1200,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Start this week',
    lesson: { headline: 'Grocery stores are engineered to drain your wallet', body: 'Every layout, end-cap placement, and "sale" is designed to increase basket size. A list and unit-price comparison bypass most of the psychology designed to make you overspend.', xp: 10 },
  },
  {
    id: 'sp10',
    title: 'Switch to a cheaper phone plan',
    description: 'MVNOs like Mint Mobile, Visible, and Consumer Cellular run on the same networks as Verizon and AT&T at 40–60% lower cost. Average savings: $600–1,200/yr for a family of four.',
    impact: 'Save $600–1,200/yr',
    impactValue: 900,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Compare plans',
    lesson: { headline: 'You\'re paying for the brand, not the network', body: 'MVNOs lease the same tower space as major carriers. The difference is the billing. Same signal, same speeds, 40–60% lower bill.', xp: 10 },
  },
  {
    id: 'sp11',
    title: 'Put all spending on a 2% cashback card',
    description: 'Spending on a 2% cashback card vs a debit card earns $600–1,000/yr on typical household spending, paid in full each month. If you\'re already paying on time, using debit is leaving money on the table.',
    impact: 'Earn $600–1,000/yr',
    impactValue: 800,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Find the best card',
    lesson: { headline: 'Debit cards are the worst payment method for the disciplined', body: 'If you pay your balance monthly, credit cards are strictly superior to debit — purchase protection, fraud coverage, and 2% back. Debit offers none of these.', xp: 10 },
  },
  {
    id: 'sp12',
    title: 'Track prices before buying anything over $50',
    description: 'Tools like CamelCamelCamel (Amazon), Honey, and Google Shopping track price history and alert you when items drop. Buying at the right moment saves 15–40% on electronics, appliances, and household goods.',
    impact: 'Save 15–40% on big purchases',
    impactValue: 480,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Install tracker',
    lesson: { headline: 'Amazon prices change 2.5 million times per day', body: 'The "sale" you see might be manufactured urgency. Price history shows the real floor. CamelCamelCamel is free, takes 30 seconds to set up, and pays off immediately.', xp: 10 },
  },
  {
    id: 'sp13',
    title: 'Buy quality once instead of cheap twice',
    description: 'The cost-per-use of a $200 item used 500 times is $0.40. The cost-per-use of a $50 replacement bought 4 times is also $0.40 — but with 3x the hassle and often worse performance. Apply this math before cheap purchases.',
    impact: 'Spend less, own better',
    impactValue: 600,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Apply the math',
    lesson: { headline: 'Cost per use is the right metric for durable goods', body: 'A $30 pan that lasts 2 years costs more than an $80 one that lasts 10. Most people don\'t run this math — so they spend more money while feeling frugal.', xp: 10 },
  },
  {
    id: 'sp14',
    title: 'Call your insurance company for a rate review',
    description: 'Insurance companies don\'t automatically apply discounts you qualify for — bundling, security systems, loyalty, or occupation. Calling annually and asking typically yields $100–400 in savings or improved coverage.',
    impact: 'Save $100–400/yr',
    impactValue: 250,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Call for a review',
    lesson: { headline: 'Insurance discounts exist — but you have to claim them', body: 'Bundling home and auto, adding a security system, or simply requesting a rate review unlocks discounts the insurer doesn\'t voluntarily apply. They save money when you don\'t ask.', xp: 10 },
  },
  {
    id: 'sp15',
    title: 'Meal prep Sunday to cut food waste',
    description: 'The average US household wastes $1,500/yr in food — mostly produce and proteins bought with good intentions. A 90-minute Sunday prep session reduces waste 60–80% and removes daily "what\'s for dinner" decisions.',
    impact: 'Save $600–1,200/yr',
    impactValue: 900,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Start this Sunday',
    lesson: { headline: '$1,500/yr in food goes directly to the trash', body: 'The USDA estimates American families waste $1,500/yr in uneaten food. Meal prep turns "I\'ll figure it out" into prepared decisions — and saved money.', xp: 10 },
  },
  {
    id: 'sp16',
    title: 'Rotate streaming services seasonally',
    description: 'The average household subscribes to 4.7 streaming services at $15–18/month each — up to $1,008/yr. Rotating services (subscribe for a show, cancel, rotate in the next) cuts costs by 40% with minimal sacrifice.',
    impact: 'Save $400–600/yr',
    impactValue: 480,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Audit your stack',
    lesson: { headline: 'You can\'t watch all of it anyway', body: 'Most streaming services release best content in a 4–6 week window. Subscribe, binge, cancel before next billing. Captures 80% of the value at 25% of the cost.', xp: 10 },
  },
  {
    id: 'sp17',
    title: 'Amortize big purchases before you buy',
    description: 'A $3,000 vacation sounds different than $250/month. A $45,000 car at $750/month feels manageable. Thinking in monthly amortized terms reveals the true opportunity cost of large discretionary purchases.',
    impact: 'Make smarter big decisions',
    impactValue: 4000,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Use the framework',
    lesson: { headline: 'Divide any purchase by 12 — then by your hourly rate', body: 'A $3,600 watch is $300/month or 30 hours of work. Framing large purchases in those terms makes opportunity cost visceral — and often changes the decision.', xp: 10 },
  },
  {
    id: 'sp18',
    title: 'Buy a used car — 3-year-old sweet spot',
    description: 'A new car loses 15–25% of its value in year 1. Buying a 3-year-old version of the same car captures most of the remaining life at 40–50% of the original price. The 3-year-old sweet spot balances value and reliability.',
    impact: 'Save $8K–15K vs. new',
    impactValue: 10000,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'See the math',
    lesson: { headline: 'The new car smell costs you $8K in year one', body: 'Depreciation is steepest in the first 3 years. Letting someone else absorb that hit means you get 7+ years of reliable driving for 40–50 cents on the dollar.', xp: 10 },
  },
  {
    id: 'sp19',
    title: 'Use your library card for books, media, and courses',
    description: 'Modern library cards include Libby (ebooks/audiobooks), Kanopy (films), and access to LinkedIn Learning or similar services. The average avid reader saves $600–1,200/yr vs. purchasing books and audiobooks.',
    impact: 'Save $600–1,200/yr',
    impactValue: 800,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Get your card',
    lesson: { headline: 'A library card is a $1,200/yr subscription you already pay for', body: 'Library taxes are baked into your property or rent. A library card activates benefits worth hundreds per year that you\'ve already paid for and never claimed.', xp: 10 },
  },
  {
    id: 'sp20',
    title: 'Apply the 48-hour rule on non-essential purchases',
    description: 'Before any non-essential purchase over $30, wait 48 hours. Studies show 70% of impulse purchases are abandoned during the wait. The items you still want after 48 hours are the ones worth buying.',
    impact: 'Cut impulse spending 70%',
    impactValue: 1500,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Set the rule',
    lesson: { headline: 'Desire fades — value doesn\'t', body: 'Impulse purchases spike dopamine at the moment of desire, then disappoint. The 48-hour pause lets the spike pass. Purchases that survive the wait deliver real, lasting satisfaction.', xp: 10 },
  },
  {
    id: 'sp21',
    title: 'Set a monthly eating-out budget',
    description: 'The average American spends $3,000/yr eating out — often without realizing it. Setting a specific monthly restaurant budget and tracking it in real-time reduces food spending by 25–35% without going to extremes.',
    impact: 'Save $750–1,000/yr',
    impactValue: 900,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Set your limit',
    lesson: { headline: '$3,000/yr in restaurants often feels like nothing', body: 'Restaurant spending is invisible because it happens in small amounts. A $60 dinner doesn\'t feel like much. Twelve of them is $720 — before drinks or extras.', xp: 10 },
  },

  // ── OPPORTUNITY (continued) ──────────────────────────────────────────────
  {
    id: 'o6',
    title: 'Start a side income stream',
    description: 'A side income of $500–1,500/month invested consistently grows to $200,000+ in 10 years. The first $500 is the hardest — after that, systems and skills compound. Freelancing, tutoring, and consulting are the fastest starts.',
    impact: '+$500–1,500/month potential',
    impactValue: 12000,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Find your angle',
    lesson: { headline: 'Side income invested, not spent, is wealth acceleration', body: 'The difference between people who build wealth fast and people who don\'t is often a second income stream — not a higher salary. The first $500/month changes your financial trajectory permanently.', xp: 10 },
  },
  {
    id: 'o7',
    title: 'Freelance using your existing skills',
    description: 'Whatever you do professionally, someone needs it on a project basis. Freelancing your core skill — even 5 hours/week at 1.5x your hourly equivalent — generates $10,000–30,000/yr in additional income.',
    impact: '+$10K–30K/yr part-time',
    impactValue: 18000,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Post on Upwork today',
    lesson: { headline: 'Your most valuable skill is already monetizable', body: 'Employers pay one salary for one scope. Clients pay project rates for specific outcomes — often 50–100% higher per hour. Your skill has more market value than your job description suggests.', xp: 10 },
  },
  {
    id: 'o8',
    title: 'Sell unused items in your home',
    description: 'The average American household has $2,000–4,000 in unused items that could be sold. eBay, Facebook Marketplace, and Poshmark convert clutter into cash in under a week for most items.',
    impact: '$2,000–4,000 one-time',
    impactValue: 2500,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Start listing',
    lesson: { headline: 'Your home is a depreciating asset you\'re ignoring', body: 'Unused items lose value every year. Selling them now converts them at today\'s value. Most people are sitting on thousands in clutter that will eventually be donated for nothing.', xp: 10 },
  },
  {
    id: 'o9',
    title: 'Check your W-4 withholding',
    description: 'If you got a large refund last year, you\'re giving the IRS an interest-free loan. Adjusting your W-4 to withhold less puts that money in your pocket monthly — and in a HYSA earning 4.5%, that\'s real income.',
    impact: 'Reclaim up to $300/yr',
    impactValue: 300,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Adjust W-4',
    lesson: { headline: 'A tax refund is an interest-free loan you gave the IRS', body: 'The average refund is $3,200. That\'s $3,200 that could have been earning 4.5% in a HYSA all year. Correct withholding earns $144/yr — just from the timing.', xp: 10 },
  },
  {
    id: 'o10',
    title: 'Claim all home office deductions if self-employed',
    description: 'Self-employed people can deduct home office space, internet, equipment, and software. The simplified method: $5/sq ft, up to 300 sq ft. Many self-employed people miss $1,500–4,000 in legitimate deductions annually.',
    impact: 'Save $1,500–4,000 in taxes',
    impactValue: 2500,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Calculate your deduction',
    lesson: { headline: 'Self-employed tax deductions are being left on the table', body: 'The IRS allows deductions for any space used regularly and exclusively for business. Most freelancers and contractors claim far fewer deductions than they legally qualify for.', xp: 10 },
  },
  {
    id: 'o11',
    title: 'Check your Social Security earnings record',
    description: 'Errors in Social Security earnings records are common — and costly. A single year of under-reported earnings can reduce your lifetime Social Security benefit by $1,000–3,000/yr. Check your record at SSA.gov annually.',
    impact: '+$1K–3K/yr in retirement',
    impactValue: 2000,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Check SSA.gov',
    lesson: { headline: 'Social Security errors reduce your benefit permanently', body: 'Your Social Security benefit is calculated from your top 35 earning years on record. If a year was reported incorrectly and you don\'t catch it, you lose that benefit forever.', xp: 10 },
  },
  {
    id: 'o12',
    title: 'Review your life insurance coverage',
    description: 'Most people are either uninsured or underinsured. The rule of thumb: 10–12x your annual income in term life insurance. A 20-year term policy for a healthy 35-year-old costs $30–50/month for $500K coverage.',
    impact: 'Protect $500K+ at $40/mo',
    impactValue: 500000,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Get a quote',
    lesson: { headline: 'Term life insurance is the most underpriced protection in finance', body: 'A 35-year-old in good health pays ~$40/month to protect $500,000 for 20 years. That\'s $0.08 per $1,000 of protection. Most people dramatically overpay for permanent life or remain unprotected.', xp: 10 },
  },
  {
    id: 'o13',
    title: 'Negotiate your rent at renewal',
    description: 'Finding a new tenant costs landlords $1,500–3,000. That gives you leverage at renewal. Requesting a rate freeze, upgrade, or modest reduction has a 40–60% success rate for tenants who ask and have a clean record.',
    impact: 'Save $600–2,400/yr',
    impactValue: 1200,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Write the email',
    lesson: { headline: 'Landlords hate turnover more than they love rent increases', body: 'Advertising, showing, and vetting a new tenant costs 1–2 months rent. A reliable tenant asking for a flat renewal is a deal most landlords will take. Most tenants never ask.', xp: 10 },
  },
  {
    id: 'o14',
    title: 'Explore refinancing your mortgage',
    description: 'If you bought your home at a higher rate and rates have since dropped, refinancing could reduce your payment $200–600/month. The break-even is typically 18–24 months — worth it if you plan to stay.',
    impact: 'Save $200–600/month',
    impactValue: 4800,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Run the numbers',
    lesson: { headline: 'Mortgage rate difference of 1% = $131/month per $200K', body: 'On a $350K loan, dropping from 7% to 6% saves $230/month — $83,000 over the life of the loan. If you bought at peak rates, refinancing is worth calculating immediately.', xp: 10 },
  },
  {
    id: 'o15',
    title: 'Use 0% intro APR financing strategically',
    description: 'Many cards offer 0% APR for 12–18 months on purchases or balance transfers. If you have a large planned expense, using 0% financing and keeping the cash invested earns 4.5%+ while you float the purchase interest-free.',
    impact: 'Earn on cash you\'re spending',
    impactValue: 800,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Find a 0% offer',
    lesson: { headline: '0% financing is arbitrage — if you follow the rules', body: 'Keeping your cash in a HYSA while floating a large purchase at 0% earns you 4.5% on money you were going to spend anyway. The catch: pay before the promo ends. Miss it and you pay back interest.', xp: 10 },
  },
  {
    id: 'o16',
    title: 'Deduct student loan interest',
    description: 'You can deduct up to $2,500 in student loan interest per year if your income is below $95K (single) or $195K (married) — phase-out begins at $80K / $165K. Most eligible borrowers forget to claim this, leaving $500–600 in tax savings on the table.',
    impact: 'Save $500–600 in taxes',
    impactValue: 550,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Claim the deduction',
    lesson: { headline: 'Student loan interest is deductible — most people forget', body: 'This above-the-line deduction reduces your adjusted gross income even if you don\'t itemize. At the 22% bracket, $2,500 of interest deducted saves $550 in taxes.', xp: 10 },
  },
  {
    id: 'o17',
    title: 'Apply for credit card travel benefits you already have',
    description: 'Many cardholders pay for travel insurance, airport lounge access, and Global Entry ($100 fee) out of pocket when their existing credit card covers them for free. Review your card benefits — most people use fewer than half.',
    impact: 'Claim $300–500 in existing perks',
    impactValue: 400,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Review your benefits',
    lesson: { headline: 'You\'re already paying for benefits you\'re not using', body: 'Annual fees are partly justified by benefits — but only if you claim them. Most cardholders use fewer than 40% of available perks. Read the benefits guide once; it pays off every trip.', xp: 10 },
  },
  {
    id: 'o18',
    title: 'Start a Health Savings Account (HSA)',
    description: 'HSAs are triple-tax advantaged: contributions are tax-deductible, growth is tax-free, and withdrawals for medical expenses are tax-free. Unused funds roll over forever — making it a stealth retirement account.',
    impact: 'Triple tax-free growth',
    impactValue: 3850,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Open an HSA',
    lesson: { headline: 'The HSA is a stealth IRA most people underfund', body: 'After 65, HSA funds can be withdrawn for any purpose (taxed like a traditional IRA). Before 65, they\'re tax-free for medical. Maxing your HSA each year creates a powerful tax-sheltered pool.', xp: 10 },
  },
  {
    id: 'o19',
    title: 'Claim the Saver\'s Credit',
    description: 'If your income is below $36,500 (single) or $73,000 (married), contributing to a retirement account qualifies you for the Saver\'s Credit — a direct tax credit of 10–50% of contributions, up to $2,000.',
    impact: 'Up to $2,000 tax credit',
    impactValue: 2000,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Check eligibility',
    lesson: { headline: 'The Saver\'s Credit is free money for retirement contributions', body: 'Unlike deductions (which reduce taxable income), credits reduce your actual tax bill dollar-for-dollar. The Saver\'s Credit is one of the most generous and least-claimed credits in the tax code.', xp: 10 },
  },
  {
    id: 'o20',
    title: 'Request a credit limit increase',
    description: 'Requesting a credit limit increase (without spending more) lowers your credit utilization ratio and improves your credit score. Most issuers approve automatically if you\'ve been a responsible customer for 6+ months.',
    impact: '+10–30 credit score points',
    impactValue: 1500,
    category: 'opportunity',
    effort: 'instant',
    actionLabel: 'Request in the app',
    lesson: { headline: 'Higher limit + same spending = lower utilization score', body: 'If your limit goes from $5K to $10K and your balance stays at $1K, your utilization drops from 20% to 10%. That improvement reflects immediately in your next credit report.', xp: 10 },
  },
];

// Daily feed shows the first 7 — rotates in production
export const MOCK_MOVES: WealthMove[] = ALL_MOVES.slice(0, 7);

export const MOCK_WINS: WealthWin[] = [
  {
    id: '1',
    title: 'First $10K saved',
    subtitle: 'You hit a major milestone',
    value: '$10,000',
    date: new Date(2026, 3, 15),
    category: 'savings',
  },
  {
    id: '2',
    title: 'Gold tier unlocked',
    subtitle: 'Top 29% of wealth builders',
    value: 'Gold',
    date: new Date(2026, 4, 1),
    category: 'tier',
  },
  {
    id: '3',
    title: 'Debt-free on credit cards',
    subtitle: 'Paid off $3,200 in 6 months',
    value: '$3,200',
    date: new Date(2026, 4, 20),
    category: 'debt',
  },
];

export const MOCK_USER: UserProfile = {
  id: '1',
  name: 'Alex',
  tier: 'GOLD',
  score: MOCK_SCORE,
  streakDays: 23,
  wins: MOCK_WINS,
  joinedAt: new Date(2026, 0, 15),
};
