import { WealthMove, VelocityScore, WealthWin, UserProfile } from '../types';

export const MOCK_SCORE: VelocityScore = {
  total: 647,
  savings: 72,
  investment: 61,
  debt: 55,
  spending: 68,
  weeklyChange: 47,
  percentile: 71,
  tier: 'GOLD',
  tierProgress: 0.66,
};

export const ALL_MOVES: WealthMove[] = [
  // ── SAVINGS ──────────────────────────────────────────────────────────
  {
    id: 's1',
    title: 'Dead money sitting idle',
    description: 'Most checking accounts pay 0.01% interest. A high-yield savings account pays 50x more — same FDIC protection, zero added risk. The gap compounds against you every day.',
    impact: 'Up to +$500/yr',
    impactValue: 117,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Move to HYSA',
    lesson: {
      headline: 'The inflation tax on idle cash',
      body: 'Inflation runs ~3%/yr. Money at 0.01% loses real value every day. A HYSA at 5% means your savings actually grow instead of quietly shrinking.',
      xp: 10,
    },
  },
  {
    id: 's2',
    title: 'Build a real emergency fund',
    description: 'Financial advisors recommend 5–6 months of expenses saved before investing aggressively. Without it, one unexpected event sends you into debt at 20%+ APR.',
    impact: 'Risk eliminated',
    impactValue: 5000,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Set up auto-save',
    lesson: {
      headline: 'Why 5 months is the magic number',
      body: '3 months covers a short job loss. 5 months covers a real crisis — medical, layoff, unexpected expense. The difference is whether you go into debt or not.',
      xp: 10,
    },
  },
  {
    id: 's3',
    title: 'Close the savings rate gap',
    description: 'Top wealth builders save 20%+ of income. The national average is 4.6%. Every 1% more you save compounds over decades — small gaps become massive differences at retirement.',
    impact: '+$2,800/yr per %',
    impactValue: 2800,
    category: 'savings',
    effort: 'quick',
    actionLabel: 'Adjust auto-transfer',
    lesson: {
      headline: 'Your savings rate is your financial speed',
      body: 'Income matters less than what you keep. Every 1% more you save compounds over decades. The path to wealth is built in percentages, not windfalls.',
      xp: 10,
    },
  },
  {
    id: 's4',
    title: 'Round-up savings: upgrade the strategy',
    description: 'Round-up investing averages $12/month — painless, but slow. A direct auto-transfer of the same amount to an index fund returns 3x more long-term due to lower fees and compounding.',
    impact: '+$340 over 5 yrs',
    impactValue: 340,
    category: 'savings',
    effort: 'medium',
    actionLabel: 'Compare options',
    lesson: {
      headline: 'Round-ups feel good but think small',
      body: 'Behavioral psychology loves round-ups because they\'re painless. But $12/month is $144/yr. A one-time $144 index fund investment today compounds further than years of small round-ups.',
      xp: 10,
    },
  },

  // ── INVESTMENT ───────────────────────────────────────────────────────
  {
    id: 'i1',
    title: 'Capture your full employer 401k match',
    description: 'If your employer matches 401k contributions up to 6% and you contribute less, you\'re leaving free compensation on the table. No investment on earth offers a 100% instant return.',
    impact: 'Up to +$3,000/yr',
    impactValue: 1200,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Check your rate',
    lesson: {
      headline: 'A 100% return, guaranteed',
      body: 'There is no investment on earth with a 100% instant return. Your employer match is exactly that — every dollar you contribute up to the match threshold is doubled immediately.',
      xp: 10,
    },
  },
  {
    id: 'i2',
    title: 'Open a Roth IRA',
    description: 'A Roth IRA grows 100% tax-free. The 2026 max is $7,000/yr. Starting at 30, that\'s worth $500K+ at retirement — all untaxed. Every year you wait is permanent compounding lost.',
    impact: '$500K+ at 65',
    impactValue: 7000,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Open Roth IRA',
    lesson: {
      headline: 'Pay taxes now, never again',
      body: 'A Roth IRA uses after-tax dollars — the growth is 100% tax-free forever. Traditional IRA withdrawals are taxed as income at retirement. The younger you start, the bigger the difference.',
      xp: 10,
    },
  },
  {
    id: 'i3',
    title: 'Rebalance to age-appropriate allocation',
    description: 'Under 40, a 60/40 stock/bond split leaves 2–3% annual return on the table vs a 90/10 allocation. Over 20 years, that difference can exceed $80,000 on a typical balance.',
    impact: '+$80K over 20 yrs',
    impactValue: 4000,
    category: 'investment',
    effort: 'quick',
    actionLabel: 'Check allocation',
    lesson: {
      headline: 'Time horizon is your biggest asset',
      body: 'Under 40, your money has 25+ years to compound. Bonds reduce volatility but slash returns. A 90/10 split historically returns 7% vs 5% for 60/40 — that 2% gap is $80K over 20 years.',
      xp: 10,
    },
  },
  {
    id: 'i4',
    title: 'Put uninvested brokerage cash to work',
    description: 'Cash sitting in a brokerage account earns near-zero while index funds return ~10%/yr historically. Uninvested cash is a slow leak — indecision is a financial decision.',
    impact: 'Up to +$100/yr per $1K',
    impactValue: 88,
    category: 'investment',
    effort: 'instant',
    actionLabel: 'Invest cash',
    lesson: {
      headline: 'Cash in a brokerage is a tax on indecision',
      body: 'Index funds like VTSAX return ~10%/yr on average. Every day idle cash sits is a day compound interest isn\'t working for you. Indecision is a financial decision.',
      xp: 10,
    },
  },
  {
    id: 'i5',
    title: 'Switch to low-fee index funds',
    description: 'Actively managed mutual funds often charge 0.5–1.5% in fees. Equivalent Vanguard or Fidelity index funds charge 0.03%. On a $50K portfolio over 20 years, that fee gap is worth $40,000+.',
    impact: '+$40K over 20 yrs',
    impactValue: 420,
    category: 'investment',
    effort: 'medium',
    actionLabel: 'Compare funds',
    lesson: {
      headline: 'The fee you don\'t see costs the most',
      body: '0.8% doesn\'t sound like much. But on $50K over 20 years, the difference between 0.8% and 0.03% in fees is $40,000 in compounded returns. Fund fees are the silent destroyer of wealth.',
      xp: 10,
    },
  },

  // ── DEBT ─────────────────────────────────────────────────────────────
  {
    id: 'd1',
    title: 'Attack high-interest credit card debt',
    description: 'Credit cards average 22%+ APR. Every $1,000 carried costs $220/yr in interest — guaranteed, risk-free losses. No investment consistently beats paying off high-interest debt first.',
    impact: '22%+ guaranteed return',
    impactValue: 280,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Build payoff plan',
    lesson: {
      headline: 'Compound interest works both ways',
      body: 'Every principle that makes investing powerful also makes high-interest debt devastating. 22% compounding against you is the same math as 22% working for you — just in reverse.',
      xp: 10,
    },
  },
  {
    id: 'd2',
    title: 'Explore a balance transfer card',
    description: 'Many credit cards offer 0% APR for 12–18 months on balance transfers. Moving high-interest debt to a 0% card and aggressively paying it down is one of the cleanest financial arbitrage moves available.',
    impact: 'Save hundreds in interest',
    impactValue: 412,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check offers',
    lesson: {
      headline: '0% APR is legal arbitrage',
      body: 'If you owe money at 22% and can move it to 0%, you\'re not just saving interest — you\'re recapturing 22% guaranteed. That beats any stock market return, risk-free.',
      xp: 10,
    },
  },
  {
    id: 'd3',
    title: 'Refinance high-rate student loans',
    description: 'If you have private student loans above 6%, refinancing to a lower rate can save hundreds per year with no upfront cost. Takes 20 minutes to check rates and doesn\'t affect your credit score.',
    impact: 'Save $400+/yr',
    impactValue: 408,
    category: 'debt',
    effort: 'medium',
    actionLabel: 'Check rates',
    lesson: {
      headline: 'Interest rate gaps are permanent wealth leaks',
      body: 'A 1.5% lower rate on a $30K loan over 10 years saves $5,000+. Refinancing is free to apply for and takes 20 minutes. Most people never do it.',
      xp: 10,
    },
  },
  {
    id: 'd4',
    title: 'Pay more than the minimum',
    description: 'Credit card minimums are calculated to maximize interest paid over time. On a $3,000 balance at 22% APR, minimums alone take 10+ years to clear and cost thousands extra in interest.',
    impact: 'Save years of payments',
    impactValue: 2100,
    category: 'debt',
    effort: 'quick',
    actionLabel: 'Set higher payment',
    lesson: {
      headline: 'Minimums are designed to make banks rich',
      body: 'Card companies calculate minimums to maximize interest paid over time. Paying even $100/month more changes the math entirely, cutting years off your payoff date.',
      xp: 10,
    },
  },

  // ── SPENDING ─────────────────────────────────────────────────────────
  {
    id: 'sp1',
    title: 'Audit your ghost subscriptions',
    description: 'The average American pays for 4–6 subscriptions they rarely or never use. At $15/month each, that\'s $720–1,080/yr on autopilot. A 10-minute audit finds them all.',
    impact: 'Up to +$1,080/yr',
    impactValue: 180,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Review subscriptions',
    lesson: {
      headline: 'Ghost subscriptions are the sneakiest wealth drain',
      body: 'Most people underestimate monthly subscriptions by 2–3x. $15/month feels trivial, but 10 of them is $1,800/yr. The ROI test: if you forgot about it, you don\'t need it.',
      xp: 10,
    },
  },
  {
    id: 'sp2',
    title: 'Redeem your credit card rewards',
    description: 'Credit card points expire, devalue, or get clawed back. Treating rewards like a real asset — and actively redeeming them for cash or travel — adds hundreds of dollars a year most people leave on the table.',
    impact: 'Reclaim what you earned',
    impactValue: 340,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Check your rewards',
    lesson: {
      headline: 'Points are a currency with an expiration date',
      body: 'Credit card rewards are real money in a different form. They expire, devalue, or get clawed back. Treating them like any other asset — actively managed — adds hundreds of dollars a year.',
      xp: 10,
    },
  },
  {
    id: 'sp3',
    title: 'Shop your car insurance',
    description: 'The average driver saves $480/yr by getting 3 competing quotes. Insurance companies charge loyal customers more than new ones. Shopping takes 20 minutes and has no downside.',
    impact: '+$480/yr on average',
    impactValue: 480,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Get quotes',
    lesson: {
      headline: 'Loyalty is punished in insurance',
      body: 'Insurance companies offer best prices to new customers and quietly raise rates on existing ones. Shopping every 2 years is a documented, repeatable way to save $400–500/yr in 20 minutes.',
      xp: 10,
    },
  },
  {
    id: 'sp4',
    title: 'Set a dining budget',
    description: 'Dining out is the #1 budget category people consistently underestimate. The national average is $350/month. Reducing by even 20% — one fewer restaurant meal per week — saves $800+/yr.',
    impact: 'Save $800+/yr',
    impactValue: 6120,
    category: 'spending',
    effort: 'medium',
    actionLabel: 'Set a target',
    lesson: {
      headline: 'Dining is the most visible savings lever',
      body: 'Dining spend is social and emotional — which is why it scales without you noticing. Cutting one meal out per week is $800/yr redirected toward wealth.',
      xp: 10,
    },
  },
  {
    id: 'sp5',
    title: 'Audit unused gym or fitness memberships',
    description: 'If you\'re paying $40–100/month for a gym you visit less than 4x/month, the per-visit cost exceeds a boutique class. Pause, downgrade, or switch to a cheaper option.',
    impact: 'Save $400–1,200/yr',
    impactValue: 408,
    category: 'spending',
    effort: 'instant',
    actionLabel: 'Review membership',
    lesson: {
      headline: 'Sunk cost blindness keeps subscriptions alive',
      body: 'The money is already gone — that\'s not the question. The question is whether continuing serves you. Per-visit cost math cuts through emotional justification.',
      xp: 10,
    },
  },
  {
    id: 'sp6',
    title: 'Use your FSA before it expires',
    description: 'Flexible Spending Accounts are use-it-or-lose-it. If you have an FSA, check your balance before December 31 — eligible expenses include glasses, dental, prescriptions, and hundreds of OTC items.',
    impact: 'Keep what\'s yours',
    impactValue: 380,
    category: 'spending',
    effort: 'quick',
    actionLabel: 'Check FSA balance',
    lesson: {
      headline: 'FSA money is pre-tax — losing it is a double loss',
      body: 'FSA contributions come out pre-tax. Letting it expire means you paid taxes on money you spent on nothing. Use-it-or-lose-it is real — and preventable.',
      xp: 10,
    },
  },

  // ── OPPORTUNITY ──────────────────────────────────────────────────────
  {
    id: 'o1',
    title: 'Negotiate your salary',
    description: '73% of people who ask for a raise get one. The average raise from negotiation is 7–10%. A single successful negotiation compounds through every future raise, bonus, and retirement contribution for the rest of your career.',
    impact: 'Up to +$10,000+/yr',
    impactValue: 12000,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'See the strategy',
    lesson: {
      headline: 'Every salary dollar compounds for life',
      body: 'A $5K raise at 30 isn\'t just $5K/yr. It\'s the base for every future raise, bonus percentage, and 401k match. A single successful negotiation is worth $200K+ over a career.',
      xp: 10,
    },
  },
  {
    id: 'o2',
    title: 'Tax loss harvesting',
    description: 'If you hold taxable investments with unrealized losses, selling to realize those losses can offset capital gains and reduce your tax bill. You can repurchase after 30 days. Almost nobody does this.',
    impact: 'Save on taxes this year',
    impactValue: 1500,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Learn how it works',
    lesson: {
      headline: 'The government shares your losses if you ask',
      body: 'Tax loss harvesting lets you sell a losing position to offset gains and reduce your tax bill. You can buy it back after 30 days. It\'s a legal rule almost nobody uses.',
      xp: 10,
    },
  },
  {
    id: 'o3',
    title: 'Maximize your HSA',
    description: 'If you\'re on a high-deductible health plan, an HSA is the only triple-tax-advantaged account available. Contributions are pre-tax, growth is tax-free, and withdrawals for medical expenses are tax-free. After 65, use it for anything.',
    impact: 'Up to $4,300 tax-free/yr',
    impactValue: 4150,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'Check eligibility',
    lesson: {
      headline: 'Triple tax advantage — most people ignore it',
      body: 'Contributions pre-tax. Growth tax-free. Medical withdrawals tax-free. After 65, use it for anything. Most people treat an HSA as a checking account — it\'s actually the most powerful account you can have.',
      xp: 10,
    },
  },
  {
    id: 'o4',
    title: 'Improve your credit score',
    description: 'The difference between a 699 and 720 credit score can be 0.5–1% on a mortgage rate. On a $300K loan, that\'s $30,000+ over the life of the loan. Two biggest levers: on-time payments and utilization below 30%.',
    impact: 'Save $30K+ on a mortgage',
    impactValue: 840,
    category: 'opportunity',
    effort: 'medium',
    actionLabel: 'See quick wins',
    lesson: {
      headline: 'Your credit score is a price tag on every loan',
      body: 'A 22-point score difference can change your mortgage rate by 0.5%. On a $300K loan, that\'s $30,000 over the life of the loan. On-time payments and low utilization are the fastest movers.',
      xp: 10,
    },
  },
  {
    id: 'o5',
    title: 'Bank and referral bonuses',
    description: 'Banks, brokerages, and credit card companies pay $100–500 to acquire new customers. These bonuses are real money for behavior you\'d do anyway — opening an account, making a purchase, or referring a friend.',
    impact: 'Up to $500+ per offer',
    impactValue: 600,
    category: 'opportunity',
    effort: 'quick',
    actionLabel: 'Find current offers',
    lesson: {
      headline: 'Bank bonuses are the cleanest arbitrage',
      body: 'Referral and signup bonuses are free money for behavior you\'d do anyway. Banks pay to acquire customers — you\'re just capturing that value.',
      xp: 10,
    },
  },
];

// Daily feed shows the first 7 — rotates in production
export const MOCK_MOVES: WealthMove[] = ALL_MOVES.slice(0, 7);

export const MOCK_WINS: WealthWin[] = [
  {
    id: '1',
    title: 'First $10K saved',
    subtitle: 'You hit a major milestone',
    value: '$10,000',
    date: new Date(2026, 3, 15),
    category: 'savings',
  },
  {
    id: '2',
    title: 'Gold tier unlocked',
    subtitle: 'Top 29% of wealth builders',
    value: 'Gold',
    date: new Date(2026, 4, 1),
    category: 'tier',
  },
  {
    id: '3',
    title: 'Debt-free on credit cards',
    subtitle: 'Paid off $3,200 in 6 months',
    value: '$3,200',
    date: new Date(2026, 4, 20),
    category: 'debt',
  },
];

export const MOCK_USER: UserProfile = {
  id: '1',
  name: 'Alex',
  tier: 'GOLD',
  score: MOCK_SCORE,
  streakDays: 23,
  wins: MOCK_WINS,
  joinedAt: new Date(2026, 0, 15),
};
